version: '3.1'
services:
  darkness:
    build:
      context: '.'
      dockerfile: 'Dockerfile'
    container_name: alpaca-story-generator
    ports:
      - 80:80
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
